# Project: RemoteDB
# Makefile created by Dev-C++ 4.9.9.2

CPP  = g++.exe
CC   = gcc.exe
WINDRES = windres.exe
RES  = RemoteDB_private.res
OBJ  = main.o cqapplication.o ../../../Atriplex/Atriplex-HEAD/atrShared/cqhttpserver.o ../../../Atriplex/Atriplex-HEAD/gpClasses/log.o ../../../Atriplex/Atriplex-HEAD/gpClasses/cformstring.o ../../../Atriplex/Atriplex-HEAD/gpClasses/cqstringlist.o cqmyhttpserver.o ../../../Atriplex/Atriplex-HEAD/gpClasses/csql.o ../../../Atriplex/Atriplex-HEAD/gpClasses/creverselookupmap.o ../../../Atriplex/Atriplex-HEAD/atrShared/chttpserverclient.o ../../../Atriplex/Atriplex-HEAD/gpClasses/ccmdline.o ../../../Atriplex/Atriplex-HEAD/gpClasses/qcout.o cdatabaseparams.o ../../../../../../libs/C/gpClasses/seh.o $(RES)
LINKOBJ  = main.o cqapplication.o ../../../Atriplex/Atriplex-HEAD/atrShared/cqhttpserver.o ../../../Atriplex/Atriplex-HEAD/gpClasses/log.o ../../../Atriplex/Atriplex-HEAD/gpClasses/cformstring.o ../../../Atriplex/Atriplex-HEAD/gpClasses/cqstringlist.o cqmyhttpserver.o ../../../Atriplex/Atriplex-HEAD/gpClasses/csql.o ../../../Atriplex/Atriplex-HEAD/gpClasses/creverselookupmap.o ../../../Atriplex/Atriplex-HEAD/atrShared/chttpserverclient.o ../../../Atriplex/Atriplex-HEAD/gpClasses/ccmdline.o ../../../Atriplex/Atriplex-HEAD/gpClasses/qcout.o cdatabaseparams.o ../../../../../../libs/C/gpClasses/seh.o $(RES)
LIBS =  -L"c:/libs/C/cadosql/lib" moclib.a C:/Qt/4.1.4/lib/libQt3Support4.a C:/Qt/4.1.4/lib/libQtAssistantClient.a C:/Qt/4.1.4/lib/libQtCore4.a C:/Qt/4.1.4/lib/libQtDesigner4.a C:/Qt/4.1.4/lib/libQtDesignerComponents4.a C:/Qt/4.1.4/lib/libQtGui4.a C:/Qt/4.1.4/lib/libqtmain.a C:/Qt/4.1.4/lib/libQtNetwork4.a C:/Qt/4.1.4/lib/libQtOpenGL4.a C:/Qt/4.1.4/lib/libQtSql4.a C:/Qt/4.1.4/lib/libQtXml4.a C:/libs/c/cadosql/lib/cadosql.lib  
INCS =  -I"C:/Qt/4.1.4/include"  -I"C:/Qt/4.1.4/include/QtCore"  -I"C:/Qt/4.1.4/include/QtNetwork"  -I"e:/Atriplex/Atriplex-HEAD"  -I"c:/libs/C/cadosql/include" 
CXXINCS =  -I"C:/Qt/4.1.4/include"  -I"C:/Qt/4.1.4/include/QtCore"  -I"C:/Qt/4.1.4/include/QtNetwork"  -I"e:/Atriplex/Atriplex-HEAD"  -I"c:/libs/C/cadosql/include" 
BIN  = RemoteDB.exe
CXXFLAGS = $(CXXINCS) -DQT_DEBUG -DQT_CORE_LIB -D__QT__ -DATRIPLEXMISC -DGLOBAL_DEBUG_LOG     -fexceptions
CFLAGS = $(INCS)   -fexceptions
RM = rm -f

.PHONY: all all-before all-after clean clean-custom

all: all-before RemoteDB.exe all-after

include qt.mak

clean: clean-custom
	${RM} $(OBJ) $(BIN)

$(BIN): $(OBJ)
	$(CPP) $(LINKOBJ) -o "RemoteDB.exe" $(LIBS)

main.o: main.cpp
	$(CPP) -c main.cpp -o main.o $(CXXFLAGS)

cqapplication.o: cqapplication.cpp
	$(CPP) -c cqapplication.cpp -o cqapplication.o $(CXXFLAGS)

../../../Atriplex/Atriplex-HEAD/atrShared/cqhttpserver.o: ../../../Atriplex/Atriplex-HEAD/atrShared/cqhttpserver.cpp
	$(CPP) -c ../../../Atriplex/Atriplex-HEAD/atrShared/cqhttpserver.cpp -o ../../../Atriplex/Atriplex-HEAD/atrShared/cqhttpserver.o $(CXXFLAGS)

../../../Atriplex/Atriplex-HEAD/gpClasses/log.o: ../../../Atriplex/Atriplex-HEAD/gpClasses/log.cpp
	$(CPP) -c ../../../Atriplex/Atriplex-HEAD/gpClasses/log.cpp -o ../../../Atriplex/Atriplex-HEAD/gpClasses/log.o $(CXXFLAGS)

../../../Atriplex/Atriplex-HEAD/gpClasses/cformstring.o: ../../../Atriplex/Atriplex-HEAD/gpClasses/cformstring.cpp
	$(CPP) -c ../../../Atriplex/Atriplex-HEAD/gpClasses/cformstring.cpp -o ../../../Atriplex/Atriplex-HEAD/gpClasses/cformstring.o $(CXXFLAGS)

../../../Atriplex/Atriplex-HEAD/gpClasses/cqstringlist.o: ../../../Atriplex/Atriplex-HEAD/gpClasses/cqstringlist.cpp
	$(CPP) -c ../../../Atriplex/Atriplex-HEAD/gpClasses/cqstringlist.cpp -o ../../../Atriplex/Atriplex-HEAD/gpClasses/cqstringlist.o $(CXXFLAGS)

cqmyhttpserver.o: cqmyhttpserver.cpp
	$(CPP) -c cqmyhttpserver.cpp -o cqmyhttpserver.o $(CXXFLAGS)

../../../Atriplex/Atriplex-HEAD/gpClasses/csql.o: ../../../Atriplex/Atriplex-HEAD/gpClasses/csql.cpp
	$(CPP) -c ../../../Atriplex/Atriplex-HEAD/gpClasses/csql.cpp -o ../../../Atriplex/Atriplex-HEAD/gpClasses/csql.o $(CXXFLAGS)

../../../Atriplex/Atriplex-HEAD/gpClasses/creverselookupmap.o: ../../../Atriplex/Atriplex-HEAD/gpClasses/creverselookupmap.cpp
	$(CPP) -c ../../../Atriplex/Atriplex-HEAD/gpClasses/creverselookupmap.cpp -o ../../../Atriplex/Atriplex-HEAD/gpClasses/creverselookupmap.o $(CXXFLAGS)

../../../Atriplex/Atriplex-HEAD/atrShared/chttpserverclient.o: ../../../Atriplex/Atriplex-HEAD/atrShared/chttpserverclient.cpp
	$(CPP) -c ../../../Atriplex/Atriplex-HEAD/atrShared/chttpserverclient.cpp -o ../../../Atriplex/Atriplex-HEAD/atrShared/chttpserverclient.o $(CXXFLAGS)

../../../Atriplex/Atriplex-HEAD/gpClasses/ccmdline.o: ../../../Atriplex/Atriplex-HEAD/gpClasses/ccmdline.cpp
	$(CPP) -c ../../../Atriplex/Atriplex-HEAD/gpClasses/ccmdline.cpp -o ../../../Atriplex/Atriplex-HEAD/gpClasses/ccmdline.o $(CXXFLAGS)

../../../Atriplex/Atriplex-HEAD/gpClasses/qcout.o: ../../../Atriplex/Atriplex-HEAD/gpClasses/qcout.cpp
	$(CPP) -c ../../../Atriplex/Atriplex-HEAD/gpClasses/qcout.cpp -o ../../../Atriplex/Atriplex-HEAD/gpClasses/qcout.o $(CXXFLAGS)

cdatabaseparams.o: cdatabaseparams.cpp
	$(CPP) -c cdatabaseparams.cpp -o cdatabaseparams.o $(CXXFLAGS)

../../../../../../libs/C/gpClasses/seh.o: ../../../../../../libs/C/gpClasses/seh.cpp
	$(CPP) -c ../../../../../../libs/C/gpClasses/seh.cpp -o ../../../../../../libs/C/gpClasses/seh.o $(CXXFLAGS)

RemoteDB_private.res: RemoteDB_private.rc 
	$(WINDRES) -i RemoteDB_private.rc --input-format=rc -o RemoteDB_private.res -O coff 
