
INSERT INTO `scenario` ( `scenarioID`, `descr` ) VALUES ( 1, NULL );

INSERT INTO `outGeneral` ( `scenarioID`, `outGeneralID`, `simulationStartTime`, `simulationEndTime`, `completedIterations`, `version` ) VALUES ( 1, 'NAADSMXXXX', NOW(), NULL, 0, '3.1.7' );

INSERT INTO `outIteration` ( `scenarioID`, `iteration`, `diseaseEnded`, `diseaseEndDay`, `outbreakEnded`, `outbreakEndDay` ) VALUES ( 1, 1, NULL, NULL, NULL, NULL );

INSERT INTO `outDailyByProductionType` ( `day`, `descADet`, `descADir`, `descAInd`, `descAIni`, `descARing`, `descUDet`, `descUDir`, `descUInd`, `descUIni`, `descURing`, `desnAAll`, `desnUAll`, `detcAClin`, `detcUClin`, `detnAClin`, `detnUClin`, `expcADir`, `expcAInd`, `expcUDir`, `expcUInd`, `infcAAir`, `infcADir`, `infcAInd`, `infcAIni`, `infcUAir`, `infcUDir`, `infcUInd`, `infcUIni`, `infnAAir`, `infnADir`, `infnAInd`, `infnUAir`, `infnUDir`, `infnUInd`, `iteration`, `productionTypeID`, `scenarioID`, `trcADir`, `trcADirp`, `trcAInd`, `trcAIndp`, `trcUDir`, `trcUDirp`, `trcUInd`, `trcUIndp`, `tscAClin`, `tscADest`, `tscALat`, `tscANImm`, `tscASubc`, `tscASusc`, `tscAVImm`, `tscUClin`, `tscUDest`, `tscULat`, `tscUNImm`, `tscUSubc`, `tscUSusc`, `tscUVImm`, `tsdAClin`, `tsdADest`, `tsdALat`, `tsdANImm`, `tsdASubc`, `tsdASusc`, `tsdAVImm`, `tsdUClin`, `tsdUDest`, `tsdULat`, `tsdUNImm`, `tsdUSubc`, `tsdUSusc`, `tsdUVImm`, `vaccAIni`, `vaccARing`, `vaccUIni`, `vaccURing`, `vaccnAAll`, `vaccnUAll`, `zoncFoci`, `zonnFoci` ) VALUES ( 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 107, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1024945, 0, 0, 0, 0, 0, 0, 3498, 0, 0, 0, 107, 0, 0, 1024945, 0, 0, 0, 1, 0, 0, 3498, 0, 0, 0, 0, 0, 0, 0, 0, 0 );

INSERT INTO `outDailyByProductionType` ( `day`, `descADet`, `descADir`, `descAInd`, `descAIni`, `descARing`, `descUDet`, `descUDir`, `descUInd`, `descUIni`, `descURing`, `desnAAll`, `desnUAll`, `detcAClin`, `detcUClin`, `detnAClin`, `detnUClin`, `expcADir`, `expcAInd`, `expcUDir`, `expcUInd`, `infcAAir`, `infcADir`, `infcAInd`, `infcAIni`, `infcUAir`, `infcUDir`, `infcUInd`, `infcUIni`, `infnAAir`, `infnADir`, `infnAInd`, `infnUAir`, `infnUDir`, `infnUInd`, `iteration`, `productionTypeID`, `scenarioID`, `trcADir`, `trcADirp`, `trcAInd`, `trcAIndp`, `trcUDir`, `trcUDirp`, `trcUInd`, `trcUIndp`, `tscAClin`, `tscADest`, `tscALat`, `tscANImm`, `tscASubc`, `tscASusc`, `tscAVImm`, `tscUClin`, `tscUDest`, `tscULat`, `tscUNImm`, `tscUSubc`, `tscUSusc`, `tscUVImm`, `tsdAClin`, `tsdADest`, `tsdALat`, `tsdANImm`, `tsdASubc`, `tsdASusc`, `tsdAVImm`, `tsdUClin`, `tsdUDest`, `tsdULat`, `tsdUNImm`, `tsdUSubc`, `tsdUSusc`, `tsdUVImm`, `vaccAIni`, `vaccARing`, `vaccUIni`, `vaccURing`, `vaccnAAll`, `vaccnUAll`, `zoncFoci`, `zonnFoci` ) VALUES ( 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 3, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 133536, 0, 0, 0, 0, 0, 0, 461, 0, 0, 0, 0, 0, 0, 133536, 0, 0, 0, 0, 0, 0, 461, 0, 0, 0, 0, 0, 0, 0, 0, 0 );

INSERT INTO `outDailyByProductionType` ( `day`, `descADet`, `descADir`, `descAInd`, `descAIni`, `descARing`, `descUDet`, `descUDir`, `descUInd`, `descUIni`, `descURing`, `desnAAll`, `desnUAll`, `detcAClin`, `detcUClin`, `detnAClin`, `detnUClin`, `expcADir`, `expcAInd`, `expcUDir`, `expcUInd`, `infcAAir`, `infcADir`, `infcAInd`, `infcAIni`, `infcUAir`, `infcUDir`, `infcUInd`, `infcUIni`, `infnAAir`, `infnADir`, `infnAInd`, `infnUAir`, `infnUDir`, `infnUInd`, `iteration`, `productionTypeID`, `scenarioID`, `trcADir`, `trcADirp`, `trcAInd`, `trcAIndp`, `trcUDir`, `trcUDirp`, `trcUInd`, `trcUIndp`, `tscAClin`, `tscADest`, `tscALat`, `tscANImm`, `tscASubc`, `tscASusc`, `tscAVImm`, `tscUClin`, `tscUDest`, `tscULat`, `tscUNImm`, `tscUSubc`, `tscUSusc`, `tscUVImm`, `tsdAClin`, `tsdADest`, `tsdALat`, `tsdANImm`, `tsdASubc`, `tsdASusc`, `tsdAVImm`, `tsdUClin`, `tsdUDest`, `tsdULat`, `tsdUNImm`, `tsdUSubc`, `tsdUSusc`, `tsdUVImm`, `vaccAIni`, `vaccARing`, `vaccUIni`, `vaccURing`, `vaccnAAll`, `vaccnUAll`, `zoncFoci`, `zonnFoci` ) VALUES ( 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 107, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1024945, 0, 0, 0, 0, 0, 0, 3498, 0, 0, 0, 107, 0, 0, 1024945, 0, 0, 0, 1, 0, 0, 3498, 0, 0, 0, 0, 0, 0, 0, 0, 0 );

INSERT INTO `outDailyByProductionType` ( `day`, `descADet`, `descADir`, `descAInd`, `descAIni`, `descARing`, `descUDet`, `descUDir`, `descUInd`, `descUIni`, `descURing`, `desnAAll`, `desnUAll`, `detcAClin`, `detcUClin`, `detnAClin`, `detnUClin`, `expcADir`, `expcAInd`, `expcUDir`, `expcUInd`, `infcAAir`, `infcADir`, `infcAInd`, `infcAIni`, `infcUAir`, `infcUDir`, `infcUInd`, `infcUIni`, `infnAAir`, `infnADir`, `infnAInd`, `infnUAir`, `infnUDir`, `infnUInd`, `iteration`, `productionTypeID`, `scenarioID`, `trcADir`, `trcADirp`, `trcAInd`, `trcAIndp`, `trcUDir`, `trcUDirp`, `trcUInd`, `trcUIndp`, `tscAClin`, `tscADest`, `tscALat`, `tscANImm`, `tscASubc`, `tscASusc`, `tscAVImm`, `tscUClin`, `tscUDest`, `tscULat`, `tscUNImm`, `tscUSubc`, `tscUSusc`, `tscUVImm`, `tsdAClin`, `tsdADest`, `tsdALat`, `tsdANImm`, `tsdASubc`, `tsdASusc`, `tsdAVImm`, `tsdUClin`, `tsdUDest`, `tsdULat`, `tsdUNImm`, `tsdUSubc`, `tsdUSusc`, `tsdUVImm`, `vaccAIni`, `vaccARing`, `vaccUIni`, `vaccURing`, `vaccnAAll`, `vaccnUAll`, `zoncFoci`, `zonnFoci` ) VALUES ( 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 3, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 133536, 0, 0, 0, 0, 0, 0, 461, 0, 0, 0, 0, 0, 0, 133536, 0, 0, 0, 0, 0, 0, 461, 0, 0, 0, 0, 0, 0, 0, 0, 0 );

INSERT INTO `outDailyByProductionType` ( `day`, `descADet`, `descADir`, `descAInd`, `descAIni`, `descARing`, `descUDet`, `descUDir`, `descUInd`, `descUIni`, `descURing`, `desnAAll`, `desnUAll`, `detcAClin`, `detcUClin`, `detnAClin`, `detnUClin`, `expcADir`, `expcAInd`, `expcUDir`, `expcUInd`, `infcAAir`, `infcADir`, `infcAInd`, `infcAIni`, `infcUAir`, `infcUDir`, `infcUInd`, `infcUIni`, `infnAAir`, `infnADir`, `infnAInd`, `infnUAir`, `infnUDir`, `infnUInd`, `iteration`, `productionTypeID`, `scenarioID`, `trcADir`, `trcADirp`, `trcAInd`, `trcAIndp`, `trcUDir`, `trcUDirp`, `trcUInd`, `trcUIndp`, `tscAClin`, `tscADest`, `tscALat`, `tscANImm`, `tscASubc`, `tscASusc`, `tscAVImm`, `tscUClin`, `tscUDest`, `tscULat`, `tscUNImm`, `tscUSubc`, `tscUSusc`, `tscUVImm`, `tsdAClin`, `tsdADest`, `tsdALat`, `tsdANImm`, `tsdASubc`, `tsdASusc`, `tsdAVImm`, `tsdUClin`, `tsdUDest`, `tsdULat`, `tsdUNImm`, `tsdUSubc`, `tsdUSusc`, `tsdUVImm`, `vaccAIni`, `vaccARing`, `vaccUIni`, `vaccURing`, `vaccnAAll`, `vaccnUAll`, `zoncFoci`, `zonnFoci` ) VALUES ( 3, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 107, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1024945, 0, 0, 0, 0, 0, 0, 3498, 0, 0, 0, 107, 0, 0, 1024945, 0, 0, 0, 1, 0, 0, 3498, 0, 0, 0, 0, 0, 0, 0, 0, 0 );

INSERT INTO `outDailyByProductionType` ( `day`, `descADet`, `descADir`, `descAInd`, `descAIni`, `descARing`, `descUDet`, `descUDir`, `descUInd`, `descUIni`, `descURing`, `desnAAll`, `desnUAll`, `detcAClin`, `detcUClin`, `detnAClin`, `detnUClin`, `expcADir`, `expcAInd`, `expcUDir`, `expcUInd`, `infcAAir`, `infcADir`, `infcAInd`, `infcAIni`, `infcUAir`, `infcUDir`, `infcUInd`, `infcUIni`, `infnAAir`, `infnADir`, `infnAInd`, `infnUAir`, `infnUDir`, `infnUInd`, `iteration`, `productionTypeID`, `scenarioID`, `trcADir`, `trcADirp`, `trcAInd`, `trcAIndp`, `trcUDir`, `trcUDirp`, `trcUInd`, `trcUIndp`, `tscAClin`, `tscADest`, `tscALat`, `tscANImm`, `tscASubc`, `tscASusc`, `tscAVImm`, `tscUClin`, `tscUDest`, `tscULat`, `tscUNImm`, `tscUSubc`, `tscUSusc`, `tscUVImm`, `tsdAClin`, `tsdADest`, `tsdALat`, `tsdANImm`, `tsdASubc`, `tsdASusc`, `tsdAVImm`, `tsdUClin`, `tsdUDest`, `tsdULat`, `tsdUNImm`, `tsdUSubc`, `tsdUSusc`, `tsdUVImm`, `vaccAIni`, `vaccARing`, `vaccUIni`, `vaccURing`, `vaccnAAll`, `vaccnUAll`, `zoncFoci`, `zonnFoci` ) VALUES ( 3, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 3, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 133536, 0, 0, 0, 0, 0, 0, 461, 0, 0, 0, 0, 0, 0, 133536, 0, 0, 0, 0, 0, 0, 461, 0, 0, 0, 0, 0, 0, 0, 0, 0 );

INSERT INTO `outIterationByProductionType` ( `descADet`, `descADir`, `descAInd`, `descAIni`, `descARing`, `descUDet`, `descUDir`, `descUInd`, `descUIni`, `descURing`, `detcAClin`, `detcUClin`, `expcADir`, `expcAInd`, `expcUDir`, `expcUInd`, `infcAAir`, `infcADir`, `infcAInd`, `infcAIni`, `infcUAir`, `infcUDir`, `infcUInd`, `infcUIni`, `iteration`, `productionTypeID`, `scenarioID`, `trcADir`, `trcADirp`, `trcAInd`, `trcAIndp`, `trcUDir`, `trcUDirp`, `trcUInd`, `trcUIndp`, `tscAClin`, `tscADest`, `tscALat`, `tscANImm`, `tscASubc`, `tscASusc`, `tscAVImm`, `tscUClin`, `tscUDest`, `tscULat`, `tscUNImm`, `tscUSubc`, `tscUSusc`, `tscUVImm`, `vaccAIni`, `vaccARing`, `vaccUIni`, `vaccURing`, `zoncFoci` ) VALUES ( 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 107, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1024945, 0, 0, 0, 0, 0, 0, 3498, 0, 0, 0, 0, 0, 0 );

INSERT INTO `outIterationByProductionType` ( `descADet`, `descADir`, `descAInd`, `descAIni`, `descARing`, `descUDet`, `descUDir`, `descUInd`, `descUIni`, `descURing`, `detcAClin`, `detcUClin`, `expcADir`, `expcAInd`, `expcUDir`, `expcUInd`, `infcAAir`, `infcADir`, `infcAInd`, `infcAIni`, `infcUAir`, `infcUDir`, `infcUInd`, `infcUIni`, `iteration`, `productionTypeID`, `scenarioID`, `trcADir`, `trcADirp`, `trcAInd`, `trcAIndp`, `trcUDir`, `trcUDirp`, `trcUInd`, `trcUIndp`, `tscAClin`, `tscADest`, `tscALat`, `tscANImm`, `tscASubc`, `tscASusc`, `tscAVImm`, `tscUClin`, `tscUDest`, `tscULat`, `tscUNImm`, `tscUSubc`, `tscUSusc`, `tscUVImm`, `vaccAIni`, `vaccARing`, `vaccUIni`, `vaccURing`, `zoncFoci` ) VALUES ( 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 3, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 133536, 0, 0, 0, 0, 0, 0, 461, 0, 0, 0, 0, 0, 0 );

INSERT INTO `outIterationByZone` ( `finalArea`, `iteration`, `maxArea`, `maxAreaDay`, `scenarioID`, `zoneID` ) VALUES ( 0, 1, 0, 0, 1, 1 );

INSERT INTO `outIterationByZone` ( `finalArea`, `iteration`, `maxArea`, `maxAreaDay`, `scenarioID`, `zoneID` ) VALUES ( 0, 1, 0, 0, 1, 2 );

UPDATE `outIteration` SET `diseaseEndDay` = NULL, `diseaseEnded` = 0, `outbreakEndDay` = NULL, `outbreakEnded` = 0 WHERE `iteration` = 1 AND `scenarioID` = 1;

INSERT INTO `outEpidemicCurves` ( `day`, `detectedAnimals`, `detectedUnits`, `infectedAnimals`, `infectedUnits`, `iteration`, `productionTypeID`, `scenarioID` ) VALUES ( 0, 0, 0, 107, 1, 1, 1, 1 );
INSERT INTO `outEpidemicCurves` ( `day`, `detectedAnimals`, `detectedUnits`, `infectedAnimals`, `infectedUnits`, `iteration`, `productionTypeID`, `scenarioID` ) VALUES ( 0, 0, 0, 0, 0, 1, 3, 1 );

INSERT INTO `outEpidemicCurves` ( `day`, `detectedAnimals`, `detectedUnits`, `infectedAnimals`, `infectedUnits`, `iteration`, `productionTypeID`, `scenarioID` ) VALUES ( 1, 0, 0, 0, 0, 1, 1, 1 );
INSERT INTO `outEpidemicCurves` ( `day`, `detectedAnimals`, `detectedUnits`, `infectedAnimals`, `infectedUnits`, `iteration`, `productionTypeID`, `scenarioID` ) VALUES ( 1, 0, 0, 0, 0, 1, 3, 1 );
INSERT INTO `outEpidemicCurves` ( `day`, `detectedAnimals`, `detectedUnits`, `infectedAnimals`, `infectedUnits`, `iteration`, `productionTypeID`, `scenarioID` ) VALUES ( 2, 0, 0, 0, 0, 1, 1, 1 );
INSERT INTO `outEpidemicCurves` ( `day`, `detectedAnimals`, `detectedUnits`, `infectedAnimals`, `infectedUnits`, `iteration`, `productionTypeID`, `scenarioID` ) VALUES ( 2, 0, 0, 0, 0, 1, 3, 1 );
INSERT INTO `outEpidemicCurves` ( `day`, `detectedAnimals`, `detectedUnits`, `infectedAnimals`, `infectedUnits`, `iteration`, `productionTypeID`, `scenarioID` ) VALUES ( 3, 0, 0, 0, 0, 1, 1, 1 );
INSERT INTO `outEpidemicCurves` ( `day`, `detectedAnimals`, `detectedUnits`, `infectedAnimals`, `infectedUnits`, `iteration`, `productionTypeID`, `scenarioID` ) VALUES ( 3, 0, 0, 0, 0, 1, 3, 1 );

UPDATE outGeneral SET completedIterations = completedIterations + 1 WHERE scenarioID = 1;

UPDATE `outGeneral` SET `simulationEndTime` = NOW() WHERE `scenarioID` = 1;

